---
- name: Configurar MongoDB
  hosts: DBservers
  become: true

  roles:
          - role: mongodb_configuration_centos
            when: ansible_distribution == 'CentOS'

          - role: mongodb_configuration_debian
            when: ansible_distriburion == 'Debian'
