---
- name: Actualizar repositorios
  hosts: all
  become: true

  roles:
    - role: centos_upgrade
      when: ansible_distribution == 'CentOS'

    - role: debian_upgrade
      when: ansible_distribution == 'Debian'

    - role: reboot
      when: reboot in "Y, y, yes"
