---
- name: Test PokeAPI module
  hosts: localhost
  tasks:
    - name: Call pokeapi module
      pokeapi:
        pokemon: "{{ pokemon_name }}"
        #pokemon: Groudon
      register: result

#    - name: Print module result
#      debug:
#              msg: "{{ result['pokemon_data'] | json_query('ability[?is_hidden==`false`].name') }}"
    
    - name: Print module result
      debug:
              msg: |
                      Name: {{ result.pokemon_data.name }} 
                      Pokedex ID: {{ result.pokemon_data.id }} 
                      Type: 
                              {% for type in result.pokemon_data.types | json_query('type.name') %}
                              - {{ type }}
                              {% endfor %}

                      Height: {{ result.pokemon_data.height }} 
                      Weight: {{ result.pokemon_data.weight }} 
                      Abilities:
                              {% for ability in result.pokemon_data.abilities | json_query('[?is_hidden==`false`].ability.name') %}
                              - {{ ability }}
                              {% endfor %}

                      Hidden Abilities:
                              {% for ability in result.pokemon_data.abilities | json_query('[?is_hidden==`true`].ability.name') %}
                              - {{ ability }}
                              {% endfor %}
