---
- name: Test PokeAPI module
  hosts: localhost
  tasks:
    - name: Call pokeapi module
      pokeapi:
              #search_type: pokemon
              #name: Spiritomb
              search_type: "{{ search_type }}"
              name: "{{ pokemon_name }}"
      retries: 3
      delay: 10
      register: pokemon_output

    - name: Print module result
      debug:
              msg:
                      - "Name: {{ pokemon_output.pokemon_data.name }}"
                      - "Pokedex ID: {{ pokemon_output.pokemon_data.id }}"
                      - "Types: {% for type in pokemon_output.pokemon_data.types %}{{ type.type.name }} {% endfor %}"
                      - "Height: {{ pokemon_output.pokemon_data.height }} decimetres"
                      - "Weight: {{ pokemon_output.pokemon_data.weight }} hectograms"
                      - "Abilities: {% for ability in pokemon_output.pokemon_data.abilities | json_query('[?is_hidden==`false`].ability.name') %}{{ ability }} {% endfor %}"
                      - "Hidden Abilities: {% for ability in pokemon_output.pokemon_data.abilities | json_query('[?is_hidden==`true`].ability.name') %}{{ ability }} {% endfor %}"
