---
- name: Test PokeAPI module
  hosts: localhost
  tasks:
    - name: Call pokeapi module
      pokeapi:
        pokemon: "{{ pokemon_name }}"
        #pokemon: Groudon
      register: result

    - name: Print module result
      debug:
        #var: result | json_query('pokemon_data.[name, id, height, weight]')
              msg: |
                      Name: {{ result.pokemon_data.name }} 
                      Pokedex ID: {{ result.pokemon_data.id }} 
                      Height: {{ result.pokemon_data.height }} 
                      Weight: {{ result.pokemon_data.weight }} 
                      Ability 1: {{ result.pokemon_data.abilities.ability.name }} 
                      Ability 2: {{ result.pokemon_data.abilities.ability.name }}
