---

- name: Recovery Backup Wordpress DataBase
  hosts: DBservers
  become: true

  roles:
          - role: restore_backup_centos
            when: ansible_distribution == "CentOS"

          - role: restore_backup_debian
            when: ansible_distribution == "Debian"
