---
- name: Instalar MongoDB
  #hosts: DBservers
  hosts: 192.168.10.62
  become: true

  roles:
          - role: mongodb_centos
            when: ansible_distribution == 'CentOS'

            #          - role: mongodb_debian
            #            when: ansible_distriburion == 'Debian'
