---
- name: Obtener espacio en los volúmenes y almacenarlo en una variable
  ansible.builtin.shell: df -h
  register: volume_space

- name: Mostrar el espacio disponible
  debug:
          msg: "{{ volume_space.stdout }}"
