---
- name: Añadir key del repo
  rpm_key:
          key: https://www.mongodb.org/static/pgp/server-{{ mongodb_version }}.asc

- name: Instalar repo
  yum_repository:
          name: "MongoDB Repository"
          baseurl: "https://repo.mongodb.org/yum/redhat/{{ server_version }}/mongodb-org/{{ mongodb_version }}/x86_64/"
          enabled: true

- name: Instalar MongoDB
  become: yes
  yum:
    name: mongodb-org
    state: present
  notify: "start mongodb"
