---
- name: Configurar Proxy
  hosts: "Proxies Inversos"
  become: true

  roles:
    - role: proxy_centos
      when: ansible_distribution == 'CentOS'

    - role: proxy_debian
      when: ansible_distribution == 'Debian'
